name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: imenei
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
          
      - name: Deploy to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create or switch to output branch
          git checkout --orphan output 2>/dev/null || git checkout output
          git reset --hard
          
          # Move generated files
          mv -f dist/*.svg ./ 2>/dev/null || true
          
          # Add and commit
          git add *.svg
          git commit -m "Update snake animation" || exit 0
          git push origin output --force
